version: '3'

services:
  web:
    build: .
    command: gunicorn simple_todo.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

    container_name: simple_todo      