# Generated by Django 4.2.16 on 2024-09-10 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-release_date'], 'verbose_name': 'Version', 'verbose_name_plural': 'Versions'},
        ),
        migrations.AddField(
            model_name='version',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(max_length=20),
        ),
    ]
