# Generated by Django 4.2.16 on 2024-09-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_status_options_status_is_default_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Catagories'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-name'], 'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
    ]
