# Generated by Django 4.2.16 on 2024-09-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_userprofile_show_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_confirmations',
            field=models.BooleanField(default=True),
        ),
    ]
